### ISSUE TITLE
Can this package be made available for osx-arm64?

### ISSUE THREAD

**Issue by robvanmieghem** [conda-forge/time-machine-feedstock#15]

**Comment by bollwyvl** [comment]
One can make a pull request to https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/main/recipe/migrations/osx_arm64.txt adding `time-machine`. This would trigger any upstream dependency rebuilds as well, all under emulation, which can take some time, as each step in the chain could uncover even build-time issues.

As I don't use (or support) anyone using this package on that architecture, I have no way to test them, so I generally don't go _looking_ for this extra work.

**Comment by bollwyvl** [comment]
Some time after https://github.com/conda-forge/time-machine-feedstock/runs/17754617057 finishes and CDN is refreshed, it should be possible to install and test the package on the platform in question. 

Will close this out: anyone who is so-equipped is welcome to test this out, and open a new issue if anything crops up.

**Comment by svaningelgem** [comment]
Thanks. When it is available on forge @robvanmieghem can check it out and do the necessary steps if needed.

**Comment by robvanmieghem** [comment]
works great
